Json Serialize Bite
pybites/rust-bite-exercises pull request #2
Opened 2024-09-02 16:26 UTC by Tanner-Ray-Martin

Fixes #1

2024-09-02 16:40 UTC, bbelderbos requested changes

2024-09-02 16:40 UTC, bbelderbos commented on serialize_json/exercise.md
> +GitHub to credit (leave blank if existing PR user):
I think I need to update the template to have authors include the exact dependency string from Cargo.toml, or what if we require this file to be included?

2024-09-02 16:40 UTC, bbelderbos commented on serialize_json/exercise.md
> +Update the serialize_person function to convert a Person instance to Json.
this makes me realize that it might be good for the description to support markdown2html on the platform

2024-09-02 16:40 UTC, bbelderbos commented on serialize_json/main.rs
> +    // your code here to return a JSON string
where is the solution? should I update the template for author to include a main.rs and a main-template.rs file?

2024-09-02 16:40 UTC, bbelderbos commented on serialize_json/main.rs
> +    fn test_serialize() {
nice

2024-09-02 16:40 UTC, bbelderbos commented on serialize_json/exercise.md
> +GitHub to credit (leave blank if existing PR user):
we need this here right?

```
serde = { version = "1", features = ["derive"] }
serde_json = "1"
```

2024-09-02 16:41 UTC, bbelderbos commented on serialize_json/exercise.md
> +GitHub to credit (leave blank if existing PR user):
thanks a lot for this first bite btw, cannot wait to put it live, author field == link to your github

2024-09-02 16:52 UTC, bbelderbos commented
Hope this addresses above needs: https://github.com/pybites/rust-bite-exercises/pull/3 - thanks.

2024-09-02 23:59 UTC, Tanner-Ray-Martin commented on serialize_json/exercise.md
> +GitHub to credit (leave blank if existing PR user):
added link to github

2024-09-03 00:00 UTC, Tanner-Ray-Martin commented on serialize_json/exercise.md
> +[dependencies]
added depencies from Cargo.toml is this a good format? should be easiest for copy pasta.

2024-09-03 00:02 UTC, Tanner-Ray-Martin commented on serialize_json/main.rs
> +fn serialize_person(person: &Person) -> String {
working solutions for the template

2024-09-03 06:40 UTC, bbelderbos commented on serialize_json/exercise.md
> +[dependencies]
in the template we have you add the Cargo.toml file itself which I think is realistic/reasonable, but listing the deps here is fine too for this one.

2024-09-03 06:40 UTC, bbelderbos commented on serialize_json/main.rs
> +fn serialize_person(person: &Person) -> String {
thanks

2024-09-03 06:41 UTC, bbelderbos approved these changes
thanks, looks good, I will add it to the platform.

2024-09-03 06:41 UTC, bbelderbos commented on serialize_json/main-template.rs
> +    // return a JSON string from the given Person instance
this is nice, I like the extra file, because we cannot assume it's a matter of taking away all the code, maybe the author wants to leave part of it and/or hide the type hints, etc

2024-09-03 06:41 UTC, merged